language: node_js
sudo: false
branches:
    only:
        - master
        - qc
node_js:
    - "0.12.5"
    - "4"
    - "6"
    - "8"
    - "10"
after_success: npm run coverage
script:
    - npm test
