language: node_js
branches:
    only:
        - master
        - qc
node_js:
    - "4"
    - "6"
    - "8"
    - "node"
before_script:
    - npm run build
script:
    - npm test
after_script:
    - npm run coverage
    - npm run coveralls
